version: "3.3"
services:
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./templates:/etc/nginx/templates
      - ./web:/usr/share/nginx/web
    ports:
      - 80:80
    environment:
      SERVER_URL: ${SERVER_URL}
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - 8080
      - 9990:9990
    volumes:
      - ./keycloak/utils:/var/tmp
      - ./keycloak/startup-scripts:/opt/jboss/startup-scripts
    command:
      - -b=0.0.0.0
      - -bmanagement=0.0.0.0
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
