version: "3.3"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./templates:/etc/nginx/templates
      - ./../web/dist:/usr/share/nginx/web
    ports:
      - 80:80
      - 443:443
    environment:
      SERVER_URL: ${SERVER_URL}
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - 8080
      - 9990:9990
    restart: always
    volumes:
      - ./../keycloak/utils:/var/tmp
      - ./../keycloak/startup-scripts:/opt/jboss/startup-scripts
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    command:
      - -b=0.0.0.0
      - -bmanagement=0.0.0.0
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

volumes:
  postgres-data:
  keycloak-data:
