version: "3.7"

services:
  nginx:
    container_name: horarbus_nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
      target: ${ENV}
      args:
        - SSL_CERTS_PATH=${SSL_CERTS_PATH}
    restart: always
    volumes:
      - ./../web:/app/web
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    networks:
      - horarbus

  node:
    container_name: horarbus_node
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
      target: ${ENV}
    entrypoint: /app/entrypoint.sh
    volumes:
      - ./../web:/app/web
      - horarbus-node-modules:/app/web/node_modules # Ignore
      - /app/web/.git # Ignore
    environment:
      NODE_ENV: ${ENV}
    networks:
      - horarbus

networks:
  horarbus:
    driver: bridge

volumes:
  horarbus:
    driver: local
    driver_opts:
      type: none
      device: ./../web
      o: bind
  horarbus-node-modules:
