name: Frontend validation
on: [push]
jobs:
    Frontend-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"
            - run: npm install
              working-directory: ./web
            - run: npm run lint
              working-directory: ./web
            - run: npm run test
              working-directory: ./web

        # Backend-Actions:
        #   runs-on: ubuntu-latest
        #   steps:
