name: Automatic check
on: [push]
jobs:
    Frontend-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"
            - run: npm install
              working-directory: ./web
            - run: npm run lint
              working-directory: ./web
            - run: npm run test
              working-directory: ./web
            - run: npm run build
              working-directory: ./web

    Backend-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup JDK
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"
                  cache: gradle
            - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
            - name: Set permissions
              run: chmod +x ./gradlew
              working-directory: ./server
            - name: Tests
              run: ./gradlew test
              working-directory: ./server
            - name: Build
              run: ./gradlew build
              working-directory: ./server
            - name: Cleanup cache
              run: |
                  rm -f ~/.gradle/caches/modules-2/modules-2.lock
                  rm -f ~/.gradle/caches/modules-2/gc.properties
